### ISSUE TITLE
Unclear how to determine widget key for config.json

### ISSUE THREAD

**Issue by dskvr** [atika/Ubersicht-Position#1]
Documentation does not include information about how to obtain a key. These days, there are several conventions for widgets, and the example only accounts for the "single-file-coffee" case. I was able to get the "single-file-jsx" case working, but was unable to get the "multi-file-jsx" case to work.

For example: 
✅ **Single File Coffee** 
```
my-widget.coffee -> my-widget-coffee
```
✅ **Single File JSX**
```
my-widget.jsx -> my-widget-jsx
```
❌ **Folder**
```
my-widget.widget/index.jsx -> ? 
```
_I have tried..._
```
my-widget-widget-index-jsx
my-widget-widget_index-jsx
my-widget-widget/index-jsx
```

Please clarify, thank you!

**Comment by atika** [comment]
You don't have to determine the ID of the widget, the __Widget ID__ appears on the __Übersicht  menu__, or with the developer tools as the HTML ID.

![Capture d’écran 2021-07-06 à 11 17 09](https://user-images.githubusercontent.com/1880360/124584575-5206f300-de4c-11eb-88b9-b1dddc673167.jpg)

If it does not work, it's elsewhere on the CSS definition.

**Comment by dskvr** [comment]
Thanks!
